/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBaseV1Callee, IBaseV1CalleeInterface } from "../IBaseV1Callee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "hook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBaseV1Callee__factory {
  static readonly abi = _abi;
  static createInterface(): IBaseV1CalleeInterface {
    return new utils.Interface(_abi) as IBaseV1CalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBaseV1Callee {
    return new Contract(address, _abi, signerOrProvider) as IBaseV1Callee;
  }
}
