/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IGame, IGameInterface } from "../IGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "setGameId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "settleAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGame__factory {
  static readonly abi = _abi;
  static createInterface(): IGameInterface {
    return new utils.Interface(_abi) as IGameInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IGame {
    return new Contract(address, _abi, signerOrProvider) as IGame;
  }
}
