/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRandom, IRandomInterface } from "../IRandom";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "height",
        type: "uint256",
      },
    ],
    name: "heightToRandom",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "height",
        type: "uint256",
      },
    ],
    name: "requestRandom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRandom__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomInterface {
    return new utils.Interface(_abi) as IRandomInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandom {
    return new Contract(address, _abi, signerOrProvider) as IRandom;
  }
}
