/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRewardable, IRewardableInterface } from "../IRewardable";

const _abi = [
  {
    inputs: [
      {
        internalType: "enum Reward.Type",
        name: "_type",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "key",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "addRound",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRewardable__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardableInterface {
    return new utils.Interface(_abi) as IRewardableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRewardable {
    return new Contract(address, _abi, signerOrProvider) as IRewardable;
  }
}
