/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISettleable, ISettleableInterface } from "../ISettleable";

const _abi = [
  {
    inputs: [],
    name: "settleAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISettleable__factory {
  static readonly abi = _abi;
  static createInterface(): ISettleableInterface {
    return new utils.Interface(_abi) as ISettleableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISettleable {
    return new Contract(address, _abi, signerOrProvider) as ISettleable;
  }
}
